sudo: required
services:
- docker
before_install:
- docker build -t calexa22/docker-react-test -f Dockerfile.dev .
script:
- docker run -e CI=true calexa22/docker-react-test yarn test
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react-test
  env: Dockerreacttest-env
  bucket_name: elasticbeanstalk-us-east-2-984595019613
  bucket_path: docker-react-test
  on:
    branch: main
  access_key_id:
    secure: $ACCESS_KEY
  secret_access_key:
    secure: $SECRET_KEY
